version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "21:00"
  open-pull-requests-limit: 0
  ignore:
  - dependency-name: vsce
    versions:
    - 1.85.0
    - 1.85.1
  - dependency-name: vscode-test
    versions:
    - 1.5.0
    - 1.5.1
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.2
    - 4.16.1
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.21.0
  - dependency-name: "@types/vscode"
    versions:
    - 1.53.0
  - dependency-name: typescript
    versions:
    - 4.2.2
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.2
    - 4.16.1
